apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fulfill-order-deployment
  labels:
    app: fulfill-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfill-order
  template:
    metadata:
      labels:
        app: fulfill-order
    spec:
      containers:
        - name: fulfill-order
          image: shanepeckham/fulfillorderack:v6
          env:
            - name: MONGOHOST
              value: mongodb://team5orders:5lk87DLIPQpHUSkz1EE9oEmQjnDsTtRgj554s6YEvxPPBeya4gTjsBUzC5oUtoZ7e7fvxFELsSd4lmIAJW3bdw==@team5orders.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
            - name: TEAMNAME
              value: team5
          volumeMounts:
          - mountPath: "/orders"
            name: logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
---
apiVersion: v1
kind: Service
metadata:
  name: fulfill-order
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
