apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"enervated-unicorn-mongodb-86c55595cd","uid":"3b71ace8-26a9-11e8-a957-0a58ac1f29f6","apiVersion":"extensions","resourceVersion":"7603"}}
  creationTimestamp: 2018-03-13T10:28:12Z
  generateName: enervated-unicorn-mongodb-86c55595cd-
  labels:
    app: enervated-unicorn-mongodb
    pod-template-hash: "4271115178"
  name: enervated-unicorn-mongodb-86c55595cd-ggdjh
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: enervated-unicorn-mongodb-86c55595cd
    uid: 3b71ace8-26a9-11e8-a957-0a58ac1f29f6
  resourceVersion: "8199"
  selfLink: /api/v1/namespaces/default/pods/enervated-unicorn-mongodb-86c55595cd-ggdjh
  uid: 3b79a31e-26a9-11e8-a957-0a58ac1f29f6
spec:
  containers:
  - env:
    - name: MONGODB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: enervated-unicorn-mongodb
    - name: MONGODB_USERNAME
    - name: MONGODB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-password
          name: enervated-unicorn-mongodb
    - name: MONGODB_DATABASE
    image: bitnami/mongodb:3.7.1-r0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: enervated-unicorn-mongodb
    ports:
    - containerPort: 27017
      name: mongodb
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - mongo
        - --eval
        - db.adminCommand('ping')
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/mongodb
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7cpt2
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: aks-nodepool1-33796387-3
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.alpha.kubernetes.io/notReady
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.alpha.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: enervated-unicorn-mongodb
  - name: default-token-7cpt2
    secret:
      defaultMode: 420
      secretName: default-token-7cpt2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T10:29:15Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T10:32:55Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T10:29:15Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://016d5797e3651538ab1550b8b5c98822cb6d6ab4dbb3a2343fcafe3c3eb06d56
    image: bitnami/mongodb:3.7.1-r0
    imageID: docker-pullable://bitnami/mongodb@sha256:282da064c466aedca69963ea54970e63c457b1d9243f2af8fff5464fde71e9f4
    lastState:
      terminated:
        containerID: docker://86fd938a4cbe6d3b612783d5d49df10ca557515e14347b6457e8077997ac6250
        exitCode: 1
        finishedAt: 2018-03-13T10:32:38Z
        reason: Error
        startedAt: 2018-03-13T10:32:25Z
    name: enervated-unicorn-mongodb
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: 2018-03-13T10:32:40Z
  hostIP: 10.240.0.7
  phase: Running
  podIP: 10.244.3.6
  qosClass: Burstable
  startTime: 2018-03-13T10:29:15Z
