apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: order-capture-deployment
  labels:
    app: order-capture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-capture
  template:
    metadata:
      labels:
        app: order-capture
    spec:
      containers:
        - name: order-capture
          image: shanepeckham/captureorderack:v6
          ports:
            - containerPort: 8080
          env:
            - name: MONGOHOST
              value: mongodb://team5orders:5lk87DLIPQpHUSkz1EE9oEmQjnDsTtRgj554s6YEvxPPBeya4gTjsBUzC5oUtoZ7e7fvxFELsSd4lmIAJW3bdw==@team5orders.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
            - name: TEAMNAME
              value: team5  
            - name: RABBITMQHOST
              value: amqp://user:iLTAGPJBQ7@intentional-camel-rabbitmq.default.svc.cluster.local:5672
---
apiVersion: v1
kind: Service
metadata:
  name: order-capture
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: order-capture
  type: LoadBalancer  
status:
  loadBalancer:
    ingress:
      - ip: 52.168.52.12