apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: order-capture-deployment
  labels:
    app: order-capture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-capture
  template:
    metadata:
      labels:
        app: order-capture
    spec:
      containers:
        - name: order-capture
          image: shanepeckham/captureorderack:v6
          ports:
            - containerPort: 8080
          env:
            - name: MONGOHOST
              value: mongodb://enervated-unicorn-mongodb.default.svc.cluster.local
            - name: TEAMNAME
              value: team5  
---
apiVersion: v1
kind: Service
metadata:
  name: order-capture
spec:
  ports:
    - port: 8080
  selector:
    app: order-capture