---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fulfill-order-deployment
  labels:
    app: fulfill-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fulfill-order
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fulfill-order
    spec:
      containers:
        - name: fulfill-order
          image: shanepeckham/fulfillorderack:v6
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: 100m
            requests:
              memory: "256Mi"
              cpu: 100m
          env:
            - name: MONGOHOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-host-secret
                  key: mongodb-host-secret
            - name: TEAMNAME
              value: team5
          volumeMounts:
          - mountPath: "/orders"
            name: logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
