apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"intentional-camel-rabbitmq-6cd8467c87","uid":"8086bbcf-26c0-11e8-a957-0a58ac1f29f6","apiVersion":"extensions","resourceVersion":"22527"}}
  creationTimestamp: 2018-03-13T13:14:46Z
  generateName: intentional-camel-rabbitmq-6cd8467c87-
  labels:
    app: intentional-camel-rabbitmq
    pod-template-hash: "2784023743"
  name: intentional-camel-rabbitmq-6cd8467c87-z6mfg
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: intentional-camel-rabbitmq-6cd8467c87
    uid: 8086bbcf-26c0-11e8-a957-0a58ac1f29f6
  resourceVersion: "22816"
  selfLink: /api/v1/namespaces/default/pods/intentional-camel-rabbitmq-6cd8467c87-z6mfg
  uid: 8088b096-26c0-11e8-a957-0a58ac1f29f6
spec:
  containers:
  - env:
    - name: RABBITMQ_USERNAME
      value: user
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          key: rabbitmq-password
          name: intentional-camel-rabbitmq
    - name: RABBITMQ_ERL_COOKIE
      valueFrom:
        secretKeyRef:
          key: rabbitmq-erlang-cookie
          name: intentional-camel-rabbitmq
    - name: RABBITMQ_NODE_PORT_NUMBER
      value: "5672"
    - name: RABBITMQ_NODE_TYPE
      value: stats
    - name: RABBITMQ_NODE_NAME
      value: rabbit@localhost
    - name: RABBITMQ_CLUSTER_NODE_NAME
    - name: RABBITMQ_VHOST
      value: /
    - name: RABBITMQ_MANAGER_PORT_NUMBER
      value: "15672"
    - name: RABBITMQ_DISK_FREE_LIMIT
      value: '"6GiB"'
    image: bitnami/rabbitmq:3.7.4-r1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - rabbitmqctl
        - status
      failureThreshold: 6
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: intentional-camel-rabbitmq
    ports:
    - containerPort: 4369
      name: epmd
      protocol: TCP
    - containerPort: 5672
      name: amqp
      protocol: TCP
    - containerPort: 25672
      name: dist
      protocol: TCP
    - containerPort: 15672
      name: stats
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - rabbitmqctl
        - status
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/rabbitmq
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-7cpt2
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: aks-nodepool1-33796387-1
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.alpha.kubernetes.io/notReady
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.alpha.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: intentional-camel-rabbitmq
  - name: default-token-7cpt2
    secret:
      defaultMode: 420
      secretName: default-token-7cpt2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T13:15:49Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T13:17:56Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-13T13:15:49Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://eed7d0d83a3f55062199017afccb442494fb525474eabf08c48a6ac73be1cf3b
    image: bitnami/rabbitmq:3.7.4-r1
    imageID: docker-pullable://bitnami/rabbitmq@sha256:3b332811b96c4b83d6e2d19db31e0b76a5f47a2a38b353bd7ae3fbf33621f12f
    lastState: {}
    name: intentional-camel-rabbitmq
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-03-13T13:17:32Z
  hostIP: 10.240.0.5
  phase: Running
  podIP: 10.244.5.25
  qosClass: Burstable
  startTime: 2018-03-13T13:15:49Z