---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: order-capture-deployment
  namespace: default
  labels:
    app: order-capture
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: order-capture
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
