---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: order-capture-deployment
  labels:
    app: order-capture
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-capture
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order-capture
    spec:
      containers:
        - name: order-capture
          image: shanepeckham/captureorderack:v6
          # securityContext:
          #   runAsNonRoot: true
          #   capabilities:
          #     drop:
          #      - SETUID
          #      - SETGID
          # resources:
          #  limits:
          #   memory: "5Gi"
          #   cpu: 100m
          #  requests:
          #   memory: "2Gi"
          #   cpu: 100m
          ports:
            - containerPort: 8080
          env:
            - name: MONGOHOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-host-secret
                  key: mongodb-host-secret
            - name: TEAMNAME
              value: team5
            - name: RABBITMQHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-host-secret
                  key: rabbitmq-host-secret
