---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: order-capture-deployment
  labels:
    app: order-capture
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-capture
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: order-capture
    spec:
      containers:
        - name: order-capture-0
          image: shanepeckham/captureorderack:v6
          ports:
            - containerPort: 8080
          env:
            - name: MONGOHOST
              value: mongodb://team5orders:5lk87DLIPQpHUSkz1EE9oEmQjnDsTtRgj554s6YEvxPPBeya4gTjsBUzC5oUtoZ7e7fvxFELsSd4lmIAJW3bdw==@team5orders.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
            - name: TEAMNAME
              value: team5  
            - name: EVENTURL
              value: https://team5orders.servicebus.windows.net/orders
            - name: EVENTPOLICYNAME
              value: RootManageSharedAccessKey
            - name: EVENTPOLICYKEY
              value: FF0SwANe0tTw7TN1bu4z4KacAOm01kyaV+8aiCL2zSI=
            - name: PARTITIONKEY
              value: "0"
        - name: order-capture-1
          image: shanepeckham/captureorderack:v6
          ports:
            - containerPort: 8080
          env:
            - name: MONGOHOST
              value: mongodb://team5orders:5lk87DLIPQpHUSkz1EE9oEmQjnDsTtRgj554s6YEvxPPBeya4gTjsBUzC5oUtoZ7e7fvxFELsSd4lmIAJW3bdw==@team5orders.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
            - name: TEAMNAME
              value: team5  
            - name: EVENTURL
              value: https://team5orders.servicebus.windows.net/orders
            - name: EVENTPOLICYNAME
              value: RootManageSharedAccessKey
            - name: EVENTPOLICYKEY
              value: FF0SwANe0tTw7TN1bu4z4KacAOm01kyaV+8aiCL2zSI=
            - name: PARTITIONKEY
              value: "1"
        - name: order-capture-2
          image: shanepeckham/captureorderack:v6
          ports:
            - containerPort: 8080
          env:
            - name: MONGOHOST
              value: mongodb://team5orders:5lk87DLIPQpHUSkz1EE9oEmQjnDsTtRgj554s6YEvxPPBeya4gTjsBUzC5oUtoZ7e7fvxFELsSd4lmIAJW3bdw==@team5orders.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
            - name: TEAMNAME
              value: team5  
            - name: EVENTURL
              value: https://team5orders.servicebus.windows.net/orders
            - name: EVENTPOLICYNAME
              value: RootManageSharedAccessKey
            - name: EVENTPOLICYKEY
              value: FF0SwANe0tTw7TN1bu4z4KacAOm01kyaV+8aiCL2zSI=
            - name: PARTITIONKEY
              value: "2"
