---
apiVersion: v1
kind: Service
metadata:
  name: order-capture
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: order-capture
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#       - hostname: k8schallengeendpoint.eastus.cloudapp.azure.com
