---
apiVersion: v1
kind: Service
metadata:
  name: order-capture
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: order-capture
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 52.168.52.12
